version: "3.1"

services:

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    env_file:
      - ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  app:
    depends_on:
      - mongodb
    build: .
    image: ma/mongo-boot-api
    env_file:
      - ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    links:
      - mongodb
